/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/Foundation.h> // Unknown library


@interface GLProgram : NSObject {

}
-(id)initWithVertexShaderFilename:(id)vertexShaderFilename fragmentShaderFilename:(id)filename;
-(id)initWithVertexShaderString:(id)vertexShaderString fragmentShaderFilename:(id)filename;
-(id)initWithVertexShaderString:(id)vertexShaderString fragmentShaderString:(id)string;
@end
