/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface GPUImageFilter : NSObject{
}
-(id)init;
-(id)initWithFragmentShaderFromFile:(id)file;
-(id)initWithFragmentShaderFromString:(id)string;
-(id)initWithVertexShaderFromString:(id)string fragmentShaderFromString:(id)string2;
@end

